export default {
    data: [
            {
                tahun: 2018,
                bulan: 1,
                tiket_masuk: 786,
                total: 786,
                min_waktu: 3,
                max_waktu: 10,
                rerata_waktu: 6,
            },
            {
                tahun: 2018,
                bulan: 2,
                tiket_masuk: 356,
                total: 356,
                min_waktu: 4,
                max_waktu: 10,
                rerata_waktu: 6,
            },
            {
                tahun: 2018,
                bulan: 3,
                tiket_masuk: 278,
                total: 278,
                min_waktu: 5,
                max_waktu: 15,
                rerata_waktu: 6,
            },
            {
                tahun: 2018,
                bulan: 4,
                tiket_masuk: 201,
                total: 201,
                min_waktu: 5,
                max_waktu: 10,
                rerata_waktu: 6,
            },
            {
                tahun: 2018,
                bulan: 5,
                tiket_masuk: 453,
                total: 453,
                min_waktu: 4,
                max_waktu: 15,
                rerata_waktu: 6,
            },
            {
                tahun: 2018,
                bulan: 6,
                tiket_masuk: 453,
                total: 453,
                min_waktu: 4,
                max_waktu: 15,
                rerata_waktu: 6,
            },
        ],

}